name: Build Docker and Optional Push - Client Advisor

on:
  push:
    branches: [main, dev, demo]
  pull_request:
    branches: [main, dev, demo]
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize
  merge_group:
  workflow_dispatch:

jobs:
  docker-build:
    strategy:
      matrix:
        include:
          - app_name: byc-wa-app
            dockerfile: src/App/WebApp.Dockerfile
            password_secret: DOCKER_PASSWORD

    uses: ./.github/workflows/build-docker.yml
    with:
      registry: bycwacontainerreg.azurecr.io
      username: bycwacontainerreg
      password_secret: ${{ matrix.password_secret }}
      app_name: ${{ matrix.app_name }}
      dockerfile: ${{ matrix.dockerfile }}
      push: ${{ github.ref_name == 'main' || github.ref_name == 'dev' || github.ref_name == 'demo' || github.ref_name == 'dependabotchanges' }} 
    secrets: inherit
