name: Test Workflow with Coverage - Client Advisor

on:
  push:
    branches: [main, dev]
    # Trigger on changes in these specific paths
  pull_request:
    branches: [main, dev]
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize

jobs:
  test_client_advisor:
    
    name: Client Advisor Tests
    runs-on: ubuntu-latest
    # The if condition ensures that this job only runs if changes are in the ClientAdvisor folder
    
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: "3.11"
      - name: Set up Node.js
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: '20'
      - name: Install Frontend Dependencies
        run: |
          cd src/App/frontend
          npm install
      - name: Run Frontend Tests with Coverage
        run: |
          cd src/App/frontend
          npm run test -- --coverage
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: client-advisor-frontend-coverage
          path: |
            src/App/frontend/coverage/
            src/App/frontend/coverage/lcov-report/
            src/App/htmlcov/
      - name: Install Backend Dependencies
        run: |
          cd src/App
          python -m pip install -r requirements.txt
          python -m pip install coverage pytest-cov
      - name: Run Backend Tests with Coverage
        run: |
          cd src/App
          python -m pytest -vv --cov=. --cov-report=xml --cov-report=html --cov-report=term-missing --cov-fail-under=80 --junitxml=coverage-junit.xml
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: client-advisor-coverage
          path: |
            src/App/coverage.xml
            src/App/coverage-junit.xml
            src/App/htmlcov/
